version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - cd backend
      - python -m pip install --upgrade pip
      - pip install pytest pytest-cov flake8
      - pip install -r requirements.txt
  
  pre_build:
    commands:
      - echo "Running tests and linting..."
      - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || echo "Linting issues found, but continuing..."
      - pytest --cov=./ --cov-report=xml || echo "Some tests failed, but continuing..."
  
  build:
    commands:
      - echo "Building the backend deployment package..."
      - mkdir -p dist
      - zip -r dist/backend.zip .
      - echo "Build completed on $(date)"
  
  post_build:
    commands:
      - echo "Backend post-build phase completed"

artifacts:
  files:
    - "backend/dist/backend.zip"
    - "appspec.yml"
    - "backend/scripts/**/*"
  discard-paths: no

cache:
  paths:
    - '/root/.cache/pip' 