version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing frontend dependencies..."
      - pwd
      - ls -la
      - echo "Checking directory structure"
      - if [ -d "frontend" ]; then cd frontend; elif [ -d "../frontend" ]; then cd ../frontend; fi
      - npm install
  
  pre_build:
    commands:
      - echo "Running tests..."
      - npm test -- --watchAll=false --testEnvironment=jsdom || echo "Some tests failed, but continuing with build..."
  
  build:
    commands:
      - echo "Building the frontend..."
      - npm run build
      - echo "Build completed on $(date)"
  
  post_build:
    commands:
      - echo "Post-build phase completed successfully"
      - echo "Setting up artifact structure"
      - cd ..  # Return to root directory
      - mkdir -p artifact_output
      - echo "Copying frontend build files"
      - cp -r frontend/build/* artifact_output/
      - echo "Copying buildspecs directory"
      - cp -r buildspecs artifact_output/
      - echo "Copying root-level buildspec files"
      - cp *.yml artifact_output/ || true
      - echo "Copying deployment scripts"
      - mkdir -p artifact_output/scripts
      - cp -r scripts/* artifact_output/scripts/ || true
      - echo "Contents of the artifact_output directory:"
      - ls -la artifact_output
      - find artifact_output -type f | sort

artifacts:
  base-directory: artifact_output
  files:
    - '**/*'

cache:
  paths:
    - 'frontend/node_modules/**/*' 