version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Running frontend deployment..."
      - echo "Current directory: $(pwd)"
      - ls -la
      # No need to change directory since the build output is directly in the artifact root
  
  pre_build:
    commands:
      - echo "Preparing for deployment..."
      - echo "Contents of buildspecs directory:"
      - ls -la buildspecs || echo "buildspecs directory not found"
  
  build:
    commands:
      - echo "Preparing deployment artifacts..."
      - echo "Listing contents of current directory:"
      - ls -la
  
  post_build:
    commands:
      - echo "Post-build phase completed"
      - echo "Deployment artifacts ready"
      - echo "Retrieving S3 bucket name from CloudFormation stack output..."
      - export BUCKET_NAME=$(aws cloudformation describe-stacks --stack-name $FRONTEND_STACK_NAME --query "Stacks[0].Outputs[?OutputKey=='FrontendBucketName'].OutputValue" --output text)
      - echo "Retrieved bucket name: $BUCKET_NAME"
      - echo "Syncing build files to S3 bucket..."
      - aws s3 sync ./ s3://$BUCKET_NAME/ --delete --exclude "buildspecs/*"
      - echo "Creating CloudFront invalidation..."
      - export CLOUDFRONT_ID=$(aws cloudformation describe-stacks --stack-name $FRONTEND_STACK_NAME --query "Stacks[0].Outputs[?OutputKey=='CloudFrontDistributionId'].OutputValue" --output text)
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
      - echo "Frontend deployment to S3 completed successfully!"

artifacts:
  files:
    - '**/*'
  discard-paths: no

cache:
  paths:
    - 'node_modules/**/*' 