version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing deployment dependencies..."
      - npm install -g aws-cli
  
  pre_build:
    commands:
      - echo "Preparing for deployment..."
      - aws --version
      - aws configure set region $AWS_REGION
      - export BUCKET_NAME=$(aws cloudformation describe-stacks --stack-name $FRONTEND_STACK_NAME --query "Stacks[0].Outputs[?OutputKey=='FrontendBucketName'].OutputValue" --output text)
      - export DISTRIBUTION_ID=$(aws cloudformation describe-stacks --stack-name $FRONTEND_STACK_NAME --query "Stacks[0].Outputs[?OutputKey=='CloudFrontDistributionId'].OutputValue" --output text)
      - echo "Deploying to S3 bucket: $BUCKET_NAME with CloudFront distribution: $DISTRIBUTION_ID"
      
      # Note about Elasticsearch configuration
      - echo "Note: This deployment uses Elasticsearch credentials from SSM Parameter Store"
      - echo "The frontend is configured to connect directly to Elasticsearch"
      - echo "No need to update .env files - configuration is injected during the build process"
  
  build:
    commands:
      - echo "Deploying frontend to S3..."
      - aws s3 sync frontend/build/ s3://$BUCKET_NAME/ --delete
  
  post_build:
    commands:
      - echo "Creating CloudFront invalidation..."
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
      - echo "Deployment completed on $(date)"

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
  discard-paths: no

cache:
  paths:
    - 'node_modules/**/*' 