version: 0.0
os: linux
files:
  - source: dist/backend.zip
    destination: /tmp/
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
    - location: scripts/create_env_file.sh
      timeout: 300
      runas: root 